import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/sections/Header";
import { cn } from "@/lib/utils";
import Hero from "@/components/sections/Hero";
import Groups from "@/components/sections/Groups";
import Projects from "@/components/sections/Projects";
import About from "@/components/sections/About";
import Members from "@/components/sections/Members";
import Partners from "@/components/sections/Partners";
import Footer from "@/components/sections/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Escritório de Engenharia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={cn(inter.className, "bg-[#2B2B2B] overflow-x-hidden")}>
        <Header />
        <Hero />
        <Groups />
        <Projects />
        <About />
        <Members />
        <Partners />
        <Footer />
      </body>
    </html>
  );
}
